theme: jekyll-theme-cayman
title: Tyler Do
description: Junior Computer Science Major at UMD

header_pages:
  - index.md
  - introduction.md
  - projects.md
  - resume.md

---
layout: home
title: Home
---
